### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by andresfunes** [entrope/linux-magicmouse#6]
CC [M]  /home/andres/software/linux-magicmouse/hid-magicmouse.o
/home/andres/software/linux-magicmouse/hid-magicmouse.c: In function ‘magicmouse_setup_input’:
/home/andres/software/linux-magicmouse/hid-magicmouse.c:280:32: error: ‘struct hid_ll_driver’ has no member named ‘hidinput_input_event’
  input->event = hdev->ll_driver->hidinput_input_event;
                                ^
/home/andres/software/linux-magicmouse/hid-magicmouse.c: In function ‘magicmouse_probe’:
/home/andres/software/linux-magicmouse/hid-magicmouse.c:370:12: error: ‘struct hid_device’ has no member named ‘hid_output_raw_report’
  ret = hdev->hid_output_raw_report(hdev, feature_1, sizeof(feature_1),
            ^
/home/andres/software/linux-magicmouse/hid-magicmouse.c:377:12: error: ‘struct hid_device’ has no member named ‘hid_output_raw_report’
  ret = hdev->hid_output_raw_report(hdev, feature_2,
            ^

**Comment by entrope** [comment]
hid-magicmouse has been merged into the Linux kernel since v2.6.34.

You did not say what kernel version you are trying to compile for, so there's no way for me to diagnose your error.
If you're trying to compile for a newer kernel, just use the kernel's built-in hid-magicmouse driver.
If you're trying to compile for an older kernel, you are on your own.
